name = "emotiv-product-worker"
main = "worker.js"
compatibility_date = "2026-05-20"

[triggers]
crons = ["0 */6 * * *"]

[[kv_namespaces]]
binding = "PRODUCTS_KV"
id = "38315c95f3044ad4b71bb677d51904e1"
preview_id = "38315c95f3044ad4b71bb677d51904e1"
